project_id = "vybdoouamvxvxkjkrnyf"

[functions.claim-rewards]
verify_jwt = false

[functions.verify-wallet]
verify_jwt = false

[functions.sync-questions]
verify_jwt = false

[functions.snapshot-leaderboard]
verify_jwt = false
schedule = "0 0 * * *"

[functions.verify-phantom]
verify_jwt = false
